spring:
  application:
    name: consumer
  datasource:
    kafka:
      bootstrap-servers: s1:29092
      consumer:
        group-id: test-consumer-group
#server:
#  port: 11001
#    url: jdbc:mysql://s1:3306/test
#    data-username: root
#    data-password: QwErmysql1!
#    driver-class-name: com.mysql.cj.jdbc.Driver


#    driver-class-name: "com.mysql.cj.jdbc.Driver"

